version: "3.8"

####################
# ENVIRONMENT VARS #
####################
x-client-env: &client-env

x-api-env: &api-env
 

####################

services:
  ###################
  ### SPA SERVICE ###
  ###################
  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    networks:
      - network

  ###################
  ### API SERVICE ###
  ###################
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - ovms
    networks:
      - network

  ####################
  ### OVMS SERVICE ###
  ####################
  ovms:
    container_name: ovms
    hostname: ovms
    image: openvino/model_server:latest
    command: /ie-serving-py/start_server.sh ie_serving model
      --model_path /var/www/models
      --model_name fast-neural-style-mosaic
      --port 8080
      --rest_port 8081
    restart: on-failure
    networks:
      - network
    expose:
      - 8080
      - 8081
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./models:/var/www/models

networks:
  network:
    driver: bridge
